### ISSUE TITLE
Include title set by ep_set_title_on_pad in public view 

### ISSUE THREAD

**Issue by gberche-orange** [JohnMcLear/ep_public_view#2]
I'm experimenting using the ep_public_view plugin to index an etherpad-lite on prem installation, in order to be able to full-text search pads. Initial results with the opensource http://www.opensearchserver.com/ are quite promising. However, the title assigned through the [ep_pad_title](https://github.com/JohnMcLear/ep_pad_title) plugin don't currently seem returned by the ep_public_view plugin in the HTML output (urls of the form /public/ ).

I'd be happy to make a modest donation to the etherpad foundation if this could be a way to find a solution to have titles set by the ep_pad_title indexeable by a plain HTML crawler.

thanks in advance,

Guillaume

**Comment by JohnMcLear** [comment]
Are you sure you mean ep_pad_title?

**Comment by JohnMcLear** [comment]
@gberche-orange I think you mean this..  https://www.npmjs.com/package/ep_set_title_on_pad not ep_pad_title?

**Comment by gberche-orange** [comment]
@JohnMcLear indeed, sorry for the confusion. Issue name fixed.

**Comment by JohnMcLear** [comment]
See my previous issue comment RE emailing me directly

**Comment by JohnMcLear** [comment]
Done

**Comment by gberche-orange** [comment]
works perfect, thanks a lot!
