### ISSUE TITLE
Include Last-Modified date into public view

### ISSUE THREAD

**Issue by gberche-orange** [JohnMcLear/ep_public_view#3]
I'm experimenting using the ep_public_view plugin to index an etherpad-lite on prem installation, in order to be able to full-text search pads. Initial results with the [opensource search server](http://www.opensearchserver.com/documentation/tutorials/crawling_a_website.md) are quite promising.

However, the date of last modification of a pad is missing from the returned public view content. Is there a way to add a [Last-Modified HTTP Header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.29) or as a fallback a [meta http-equiv="Last-Modified"](https://www.w3.org/wiki/HTML/Elements/meta) field in the HTML response ?

I'd be happy to make a modest donation to the etherpad foundation to help such improvement.

**Comment by JohnMcLear** [comment]
Yea this is probably doable, it might make sense to email me to chat about your requirements directly so I can allocate some time.

**Comment by JohnMcLear** [comment]
Done

**Comment by gberche-orange** [comment]
works perfect, thanks a lot!
